const products = [
    {
        id: 1,
        title: "Wireless Headphones",
        price: 1999,
        description: "These wireless headphones offer premium sound quality, noise cancellation, Bluetooth connectivity, comfortable ear padding, long battery life, built-in microphone, and are perfect for music, gaming, meetings, and travel use.",
        category: "Electronics",
        image: "images/headphone.jpg",
    },
    {
        id: 2,
        title: "Smart Watch",
        price: 2999,
        description: "This fitness smart watch features heart rate monitoring, step tracking, sleep analysis, message notifications, waterproof design, long battery life, multiple sports modes, and connects easily to both Android and iOS devices.",
        category: "Electronics",
        image: "images/smart watch.jpg",
    },
    {
        id: 3,
        title: "T-Shirt",
        price: 499,
        description: "Made from 100% cotton, this printed T-shirt provides a soft, breathable, and stylish look, perfect for casual outings, comfortable wear at home, and fits perfectly with jeans or shorts.",
        category: "Clothing",
        image: "images/t-shirt.jpg",
    },
    {
        id: 4,
        title: "Mobiles",
        price: 39999,
        description: "This smartphone offers a high-speed experience with 64 GB RAM, powerful processor, excellent camera, sleek design, long battery life, fast charging, and supports all modern apps and games effortlessly.",
        category: "Electronics",
        image: "images/mobile.jpg",
    },
    {
        id: 5,
        title: "Shoes",
        price: 2499,
        description: "These shoes are designed for both walking and running, offering superior comfort, durable soles, breathable material, modern design, lightweight build, and are perfect for gym or everyday wear.",
        category: "Footwear",
        image: "images/shoe.jpg",
    },
    {
        id: 6,
        title: "Laptop",
        price: 69999,
        description: "Featuring 64 GB RAM and 512 GB SSD, this laptop delivers fast performance, ideal for work, gaming, and multitasking, with a slim build, long battery life, and vibrant display.",
        category: "Electronics",
        image: "images/laptop.jpg",
    },
    {
        id: 8,
        title: "Chair",
        price: 800,
        description: "This beautiful chair is crafted for style and comfort, featuring sturdy build quality, cushioned seating, ergonomic support, and a modern design, suitable for home, office, or study room.",
        category: "Furniture",
        image: "images/chair.jpeg",
    },
    {
        id: 9,
        title: "Cooling Glass",
        price: 99,
        description: "These stylish cooling glasses provide UV protection, enhance your fashion, reduce glare, offer clear vision, lightweight frame, comfortable fit, and are ideal for outdoor activities in sunny weather.",
        category: "Accessories",
        image: "images/coolingglass.jpeg",
    },
    {
        id: 10,
        title: "Mouse",
        price: 3999,
        description: "This high-quality mouse offers ergonomic design, ultra-fast response, customizable buttons, smooth tracking, wireless connectivity, long battery life, and works seamlessly for gaming, design, or regular office work.",
        category: "Electronics",
        image: "images/mouse.jpeg",
    },
    {
        id: 11,
        title: "Pant",
        price: 999,
        description: "Crafted from premium fabric, this pant is comfortable, durable, stylish, suitable for office or casual wear, features deep pockets, excellent fit, wrinkle resistance, and available in all sizes.",
        category: "Clothing",
        image: "images/pant.jpeg",
    },
    {
        id: 12,
        title: "Bottle",
        price: 299,
        description: "This bottle is made from BPA-free plastic, ideal for carrying water, durable, leak-proof, lightweight, stylish design, reusable, environmentally friendly, and perfect for school, gym, or travel use.",
        category: "Home Essentials",
        image: "images/bottle.jpeg",
    }
    // Add more product as needed
];